import { useEffect, useState } from 'react'
import { useParams, Link } from 'react-router-dom'
import { supabase } from '../lib/supabase.js'
import Badge from '../components/Badge.jsx'

function formatDate(ts) {
  if (!ts) return '—'
  return new Date(ts).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' })
}

function groupBy(arr, key) {
  return arr.reduce((acc, item) => {
    const k = item[key] || 'other'
    if (!acc[k]) acc[k] = []
    acc[k].push(item)
    return acc
  }, {})
}

function ResultRow({ result }) {
  const isFail = result.status === 'fail'
  const isWarn = result.status === 'warning'
  return (
    <div
      className={`px-5 py-4 flex items-start justify-between gap-4 ${
        isFail ? 'border-l-2 border-red-500 bg-red-50' : isWarn ? 'border-l-2 border-amber-400 bg-amber-50/40' : ''
      }`}
    >
      <div className="flex-1 min-w-0">
        <p className="text-sm font-medium text-navy-900">{result.check_name}</p>
        <div className="flex gap-6 mt-1">
          <span className="text-xs text-gray-400">Expected: <span className="text-navy-700">{result.expected_value}</span></span>
          <span className="text-xs text-gray-400">Found: <span className="text-navy-700">{result.found_value}</span></span>
        </div>
        {result.note && <p className="text-xs text-gray-400 mt-0.5 italic">{result.note}</p>}
      </div>
      <Badge status={result.status} />
    </div>
  )
}

function downloadReport(caseData, documents, fields, results) {
  const lines = []
  lines.push('VerifyTrade — Case Report')
  lines.push('='.repeat(40))
  lines.push(`Case Ref : ${caseData.case_ref}`)
  lines.push(`Client   : ${caseData.client_name || '—'}`)
  lines.push(`Date     : ${formatDate(caseData.created_at)}`)
  lines.push(`Status   : ${caseData.status}`)
  lines.push(`Result   : ${caseData.overall_result?.toUpperCase() || '—'}`)
  lines.push('')
  lines.push('DOCUMENTS UPLOADED')
  lines.push('-'.repeat(30))
  documents.forEach((d, i) => lines.push(`${i + 1}. ${d.file_name} (${d.file_type})`))
  lines.push('')
  lines.push('EXTRACTED FIELDS')
  lines.push('-'.repeat(30))
  const grouped = groupBy(fields, 'doc_type')
  Object.entries(grouped).forEach(([type, fs]) => {
    lines.push(`\n[${type}]`)
    fs.forEach((f) => lines.push(`  ${f.field_name}: ${f.field_value}`))
  })
  lines.push('')
  lines.push('VERIFICATION RESULTS')
  lines.push('-'.repeat(30))
  lines.push(`Passed: ${caseData.pass_count ?? 0} / Failed: ${caseData.fail_count ?? 0} / Review: ${caseData.warn_count ?? 0}`)
  const groupedR = groupBy(results, 'category')
  Object.entries(groupedR).forEach(([cat, rs]) => {
    lines.push(`\n${cat}`)
    rs.forEach((r) => {
      lines.push(`  [${r.status.toUpperCase()}] ${r.check_name}`)
      lines.push(`    Expected: ${r.expected_value} | Found: ${r.found_value}`)
      if (r.note) lines.push(`    Note: ${r.note}`)
    })
  })
  lines.push('\n' + '='.repeat(40))
  lines.push('Generated by VerifyTrade')

  const blob = new Blob([lines.join('\n')], { type: 'text/plain' })
  const url = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = url
  a.download = `${caseData.case_ref}-report.txt`
  a.click()
  URL.revokeObjectURL(url)
}

export default function CaseDetail() {
  const { id } = useParams()
  const [caseData, setCaseData] = useState(null)
  const [documents, setDocuments] = useState([])
  const [fields, setFields] = useState([])
  const [results, setResults] = useState([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    async function load() {
      const [{ data: c }, { data: docs }, { data: ef }, { data: vr }] = await Promise.all([
        supabase.from('cases').select('*').eq('id', id).single(),
        supabase.from('documents').select('*').eq('case_id', id).order('created_at'),
        supabase.from('extracted_fields').select('*').eq('case_id', id).order('doc_type'),
        supabase.from('verification_results').select('*').eq('case_id', id).order('category'),
      ])
      setCaseData(c)
      setDocuments(docs || [])
      setFields(ef || [])
      setResults(vr || [])
      setLoading(false)
    }
    load()
  }, [id])

  if (loading) {
    return (
      <div className="flex items-center justify-center py-32 text-sm text-gray-400">
        Loading case…
      </div>
    )
  }

  if (!caseData) {
    return (
      <div className="text-center py-32">
        <p className="font-display text-xl text-navy-900 mb-2">Case not found</p>
        <Link to="/cases" className="text-sm text-gold-500 hover:text-gold-600">← Back to cases</Link>
      </div>
    )
  }

  const passCount = caseData.pass_count ?? 0
  const failCount = caseData.fail_count ?? 0
  const warnCount = caseData.warn_count ?? 0
  const total = passCount + failCount + warnCount
  const isPassed = caseData.overall_result === 'pass'

  const groupedFields = groupBy(fields, 'doc_type')
  const groupedResults = groupBy(results, 'category')

  const docTypeLabel = (t) => ({ invoice: 'Invoice', letter_of_credit: 'Letter of Credit', bill_of_lading: 'Bill of Lading', other: 'Other' }[t] || t)

  return (
    <div>
      {/* Back */}
      <Link to="/cases" className="inline-flex items-center gap-1.5 text-sm text-gray-400 hover:text-navy-900 transition-colors mb-6 fade-in">
        <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
        </svg>
        All Cases
      </Link>

      {/* Header */}
      <div className="bg-white border border-[#E2E6EA] rounded-lg p-6 shadow-card mb-6 fade-in-1">
        <div className="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div className="flex items-center gap-3 mb-1">
              <h1 className="font-display text-2xl font-semibold text-navy-900">{caseData.case_ref}</h1>
              <Badge status={caseData.status} />
            </div>
            <p className="text-navy-600 font-medium">{caseData.client_name}</p>
            <p className="text-sm text-gray-400 mt-0.5">{formatDate(caseData.created_at)}</p>
          </div>
          <button
            onClick={() => downloadReport(caseData, documents, fields, results)}
            className="inline-flex items-center gap-2 border border-[#E2E6EA] text-navy-700 text-sm font-medium px-4 py-2 rounded hover:bg-gray-50 transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download Report
          </button>
        </div>
      </div>

      {/* Documents */}
      <div className="bg-white border border-[#E2E6EA] rounded-lg shadow-card mb-6 fade-in-2">
        <div className="px-6 py-4 border-b border-[#E2E6EA]">
          <h2 className="font-display text-lg font-semibold text-navy-900">Documents Uploaded</h2>
        </div>
        {documents.length === 0 ? (
          <p className="px-6 py-8 text-sm text-gray-400">No documents on record.</p>
        ) : (
          <ul className="divide-y divide-[#E2E6EA]">
            {documents.map((doc) => (
              <li key={doc.id} className="px-6 py-4 flex items-center gap-4">
                <div className="w-8 h-8 bg-navy-50 rounded flex items-center justify-center shrink-0">
                  <svg className="w-4 h-4 text-navy-600" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M7 21h10a2 2 0 002-2V9.414a1 1 0 00-.293-.707l-5.414-5.414A1 1 0 0012.586 3H7a2 2 0 00-2 2v14a2 2 0 002 2z" />
                  </svg>
                </div>
                <div>
                  <p className="text-sm font-medium text-navy-900">{doc.file_name}</p>
                  <p className="text-xs text-gray-400">{docTypeLabel(doc.file_type)}</p>
                </div>
              </li>
            ))}
          </ul>
        )}
      </div>

      {/* Extracted Fields */}
      {fields.length > 0 && (
        <div className="bg-white border border-[#E2E6EA] rounded-lg shadow-card mb-6 fade-in-3">
          <div className="px-6 py-4 border-b border-[#E2E6EA]">
            <h2 className="font-display text-lg font-semibold text-navy-900">Extracted Fields</h2>
          </div>
          {Object.entries(groupedFields).map(([type, fs]) => (
            <div key={type}>
              <div className="px-6 py-2 bg-[#F7F8FA] border-b border-[#E2E6EA]">
                <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">{docTypeLabel(type)}</span>
              </div>
              <div className="divide-y divide-[#E2E6EA]">
                {fs.map((f) => (
                  <div key={f.id} className="px-6 py-3 flex justify-between gap-4">
                    <span className="text-sm text-gray-400">{f.field_name}</span>
                    <span className="text-sm font-medium text-navy-900 text-right">{f.field_value}</span>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      )}

      {/* Verification Results */}
      {results.length > 0 && (
        <div className="bg-white border border-[#E2E6EA] rounded-lg shadow-card fade-in-4">
          <div className="px-6 py-4 border-b border-[#E2E6EA]">
            <h2 className="font-display text-lg font-semibold text-navy-900">Verification Results</h2>
          </div>

          {/* Summary stats */}
          <div className="grid grid-cols-4 divide-x divide-[#E2E6EA] border-b border-[#E2E6EA]">
            {[
              { label: 'Total Checks', val: total, cls: 'text-navy-900' },
              { label: 'Passed', val: passCount, cls: 'text-emerald-600' },
              { label: 'Failed', val: failCount, cls: 'text-red-600' },
              { label: 'Review', val: warnCount, cls: 'text-amber-600' },
            ].map(({ label, val, cls }) => (
              <div key={label} className="px-6 py-4 text-center">
                <p className={`font-display text-2xl font-semibold ${cls}`}>{val}</p>
                <p className="text-xs text-gray-400 mt-0.5">{label}</p>
              </div>
            ))}
          </div>

          {/* Verdict */}
          <div className={`px-6 py-4 border-b border-[#E2E6EA] ${isPassed ? 'bg-emerald-50' : 'bg-red-50'}`}>
            <div className="flex items-center gap-2">
              <div className={`w-5 h-5 rounded-full flex items-center justify-center ${isPassed ? 'bg-emerald-600' : 'bg-red-600'}`}>
                {isPassed ? (
                  <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                  </svg>
                ) : (
                  <svg className="w-3 h-3 text-white" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M6 18L18 6M6 6l12 12" />
                  </svg>
                )}
              </div>
              <p className={`text-sm font-semibold ${isPassed ? 'text-emerald-800' : 'text-red-800'}`}>
                {isPassed
                  ? 'File passes all checks — ready for bank queue'
                  : `${failCount} discrepanc${failCount === 1 ? 'y' : 'ies'} found — client notification required`}
              </p>
            </div>
          </div>

          {/* Rule rows */}
          {Object.entries(groupedResults).map(([cat, rs]) => (
            <div key={cat}>
              <div className="px-6 py-2 bg-[#F7F8FA] border-b border-[#E2E6EA]">
                <span className="text-xs font-semibold text-gray-400 uppercase tracking-wider">{cat}</span>
              </div>
              <div className="divide-y divide-[#E2E6EA]">
                {rs.map((r) => <ResultRow key={r.id} result={r} />)}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  )
}
